import { Playfair_Display, Inter } from "next/font/google";
import {
  LANGUAGE_BY_LOCALE,
  LOCALES,
  REGION_BY_LOCALE,
} from "@/config/regions";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { Footer, NavBar } from "@/components";
import ScrollToTop from "@/layouts/scroll-to-top";
import LensiScroll from "@/layouts/lensi-scroll";

export const playfairSerif = Playfair_Display({
  variable: "--font-playfair-serif",
});

export const interSans = Inter({
  variable: "--font-inter-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return LOCALES.map((locale) => ({ locale }));
}

import { getRequestConfig, setRequestLocale } from "next-intl/server";

// ... (imports)

export default async function LocaleLayout({ children, params }) {
  const { locale } = await params;
  setRequestLocale(locale);

  const lang = LANGUAGE_BY_LOCALE[locale];
  const region = REGION_BY_LOCALE[locale];

  const messages = (await import(`../../../messages/${locale}.json`)).default;

  return (
    <html lang={lang} dir={lang === "ar" ? "rtl" : "ltr"} data-region={region}>
      <body
        className={`${playfairSerif.variable} ${interSans.variable} antialiased`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ScrollToTop />

          <NavBar />

          <LensiScroll>
            <main>{children}</main>
          </LensiScroll>

          {/* Footer */}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
